server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/niumall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ccx2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #  集成邮件发送
  mail:
    host: smtp.qq.com
    username: chenbyf1314@foxmail.com
    password: nioowvafbetxbdgh
    properties.mail.smtp.ssl.enable: true #开启SSL
  cache:
    type: redis
  redis:
    lettuce:
      pool:
        max-active: 80 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 400 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
    database: 1
  servlet:
    multipart:
      max-request-size: 1GB  # 上传文件总的最大值 默认10MB
      max-file-size: 5MB #单个文件最大值 默认10MB
#mybatis plus配置
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto